export type ThreeWayLogisticsRequest = {
	requester_name?: string
	requester_phone?: string
	requester_email?: string
	requester_company_name?: string
	requester_username?: string
	supplier_company_name?: string
	supplier_contact_person?: string
	supplier_phone?: string
	supplier_city?: string
	supplier_address?: string
	supplier_date_for_visit?: string
	supplier_time_for_visit?: string
	receiver_name?: string
	receiver_company_name?: string
	receiver_phone?: string
	receiver_email?: string
	description_shipment_description?: string
	description_shipment_count?: string
	description_shipment_weight?: string
	description_additional_instructions?: string
	description_payment_sum_to_supplier?: string
	delivery_details_city?: string
	delivery_details_address?: string
	delivery_details_office?: string
	dc?: string
	dccp?: string
	email_on_delivery?: string
	invoice_before_pay?: string
	preview?: string
	test?: string
	payment_delivery_and_return_by_me?: string
	payment_return_by_me?: string
	payment_delivery_by_requester?: string
	payment_delivery_by_receiver?: string
	oc_sum?: string
	cd_sum?: string
	priority_delivery_time_before?: string
	priority_delivery_time_after?: string
	priority_delivery_time_in?: string
}
